### ISSUE TITLE
Error: Result would exceed 2^31-1 bytes"

### ISSUE THREAD

**Issue by DeFilippis** [rosawojciech/bigchess#3]
I'm trying to read in a 3 Gb file containing a huge amount of games played on LiChess:

`df <- read.pgn(paste0(path, file), add.tags = c("UTCDate", "UTCTime", "WhiteElo",  "BlackElo", "WhiteRatingDiff", "BlackRatingDiff", "WhiteTitle", "BlackTitle","TimeControl", "Termination"), n.moves = T, extract.moves = -1, stat.moves = T, big.mode = F, quiet = F, ignore.other.games = F)`

I'm getting the follow error:

> "Error in paste(subset(r2, tmp1 == "Movetext", select = c(tmp2))[, 1], : result would exceed 2^31-1 bytes"

Is this avoidable?  What do you recommend?  Thanks for your great work on this!

**Comment by rosawojciech** [comment]
It's an internal R memory limit with parsing text files using readLines() function:
[https://stackoverflow.com/questions/46139895/error-result-would-exceed-231-bytes](url)
You can find more info about that here:
[https://stat.ethz.ch/R-manual/R-devel/library/base/html/Memory-limits.html](url)
Anyway, as you probably know it's some kind of R problem that, by default it loads all data into RAM. There are several packages dealing with that, bigchess works well with ff components:
```r
require(ff)
require(ffbase)
## ... path, file..
## same syntax as yours (except with big.mode parameter which should not be used in read.pgn.ff)
fdf <- read.pgn.ff(paste0(path, file), add.tags = c("UTCDate", "UTCTime", "WhiteElo", "BlackElo", "WhiteRatingDiff", "BlackRatingDiff", "WhiteTitle", "BlackTitle","TimeControl", "Termination"), n.moves = T, extract.moves = -1, stat.moves = T, quiet = F, ignore.other.games = F)
## deal with ff.df(), after this clean-up:
delete(fdf)
```
On the other hand you can also try to pack your pgn big file (to gzip) and then load it with read.pgn().
Both cases will take long time.. but mostly it is worth waiting :)
