### ISSUE TITLE
Error in ff:  vmode 'list' not implemented

### ISSUE THREAD

**Issue by DeFilippis** [rosawojciech/bigchess#4]
```
> df <- read.pgn.ff(paste0(path, file), add.tags = c("UTCDate", "UTCTime", "WhiteElo",  "BlackElo", "WhiteRatingDiff", "BlackRatingDiff", "WhiteTitle", "BlackTitle","TimeControl", "Termination"), n.moves = T, extract.moves = -1, stat.moves = T, quiet = F, ignore.other.games = F)
2018-11-05 15:26:44, successfully imported 58633 games
2018-11-05 15:26:48, N moves computed
2018-11-05 15:26:59, extract moves done
2018-11-05 15:27:24, stat moves computed
Error in ff(initdata = initdata, length = length, levels = levels, ordered = ordered,  : 
  vmode 'list' not implemented
```

Attempting to read in my large pgn using read.pgn.ff now throws the above error.  This happens even if I gzip the file and read it in through gzfile connection. Thoughts?

**Comment by rosawojciech** [comment]
Clearly looks like a problem with add.tags. Could you send me this data or even this 60k games? Without access to this file I can't fix this.

**Comment by DeFilippis** [comment]
https://drive.google.com/file/d/1UIncNUTe9e9xVGAkJIyzv8ofl7fm-uxN/view?usp=sharing

Here's a zipped archive containing the data

**Comment by rosawojciech** [comment]
Bug fixed now, in version 1.2.3.
Remember to open your file in proper mode, for example Windows users should use "rb" option, so in your case, here is code that works fine for me:
```r
require(bigchess)
require(ff)
require(ffbase)

con <- gzfile("path_to_your_file.pgn.gz","rb")
# example of opening ungzipped file for read.pgn.ff() under Windows:
# con<- file("path_to_your_file.pgn","rb") 

fdf <- read.pgn.ff(con,stat.moves = FALSE,add.tags = c("UTCDate","UTCTime","WhiteRatingDiff",
"BlackRatingDiff","WhiteTitle","BlackTitle","WhiteElo","BlackElo","TimeControl","Termination"))
#2018-11-07 11:49:08, successfully imported 58633 games
#2018-11-07 11:49:12, N moves computed
#2018-11-07 11:49:18, extract moves done
#2018-11-07 11:49:25, batch 1 processed
#....
#2018-11-07 12:04:03, batch 31 processed
#2018-11-07 12:04:03, end of file: 1628119 games imported successfully
#work with your fdf, aggregate and save data and so on..
delete(fdf)
```

**Comment by DeFilippis** [comment]
Thanks for working on this!  Still not working for me:

```
con <- gzfile(paste0(path, file))

fdf <- read.pgn.ff(con, add.tags = c("UTCDate", "UTCTime", "WhiteElo",  "BlackElo", "WhiteRatingDiff", "BlackRatingDiff", "WhiteTitle", "BlackTitle","TimeControl", "Termination"), n.moves = T, extract.moves = -1, stat.moves = F, quiet = F, ignore.other.games = F, source.movetext = T)
```

> 
> 2018-11-07 10:45:52, successfully imported 58633 games
> 2018-11-07 10:45:57, N moves computed
> 2018-11-07 10:46:08, extract moves done
> Error in setwd(dfile) : cannot change working directory

**Comment by rosawojciech** [comment]
Well, this is not bigchess problem but ff:
[https://stackoverflow.com/questions/14629686/ff-package-on-a-server-read-table-ffdf-cannot-change-working-directory/14630934](url)
After loading ff package set your temporary directory:
```r
options(fftempdir = "path/to/your/folder")
```

**Comment by DeFilippis** [comment]
It's working now! Thanks for all your help!
