### ISSUE TITLE
read_pgn_ff never stops loading batches

### ISSUE THREAD

**Issue by DeFilippis** [rosawojciech/bigchess#5]
I tried loading the file I sent you earlier, with the following syntax (running Mac OS):

```
options(fftempdir = path)
con <- gzfile(paste0(path, file))
fdf <- read.pgn.ff(con, add.tags = c("UTCDate", "UTCTime", "WhiteElo",  "BlackElo", "WhiteRatingDiff", "BlackRatingDiff", "WhiteTitle", "BlackTitle","TimeControl", "Termination"), stat.moves = F, source.movetext = T)
```

The function appears to be working, except that it never stops loading batches.  It has been running for over three hours and is currently on Batch 158, which is far more than the games in the entire corpus.  Do you know what's going on?  Could you test it with source.movetext = T?

**Comment by DeFilippis** [comment]
But, as I mentioned, I'm not using Windows.  I'm using Mac OS

**Comment by rosawojciech** [comment]
Have you tried 'r' option (instead of 'rb')? IT works on my Ubuntu
